apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      nodePort: 30000
      protocol: TCP
  selector:
    app: python-app
