- name: install pip3
  apt: name=python3-pip state=present

- name: Install docker-compose
  pip:
    executable: pip3
    name:
      - setuptools
      - docker-compose<1.28

- name: Create a folder for docker-compose.yml
  file:
    path: "{{ apps_remote_install_path }}"
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: "{{ language }}/docker-compose.yml"
    dest: "{{ apps_remote_install_path }}/docker-compose.yml"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ apps_remote_install_path }}"
