- name: install pip3
  apt: name=python3-pip state=present

- name: Install docker-compose
  pip:
    executable: pip3
    name:
      - setuptools
      - docker-compose<1.28

- name: Create a folder for docker-compose.yml
  file:
    path: "{{ apps_remote_install_path }}"
    state: directory

- name: Create docker-compose.yml on remote host from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ apps_remote_install_path }}/docker-compose.yml"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ apps_remote_install_path }}"
