- name: Install Docker on all hosts
  hosts: all
  roles:
    - docker
  become: yes

- name: Deploy python app on python host
  hosts: python
  roles:
    - python_app
  become: yes

- name: Deploy scala app on scala host
  hosts: scala
  roles:
    - scala_app
  become: yes
