- name: Install Docker on all hosts
  hosts: all
  roles:
    - docker
  become: yes

- name: Deploy Python app on its host
  hosts: python
  vars:
    apps_remote_install_path: "/opt/python_app"
    language: "python"
  roles:
    - apps
  become: yes

- name: Deploy Scala app on its host
  hosts: scala
  vars:
    apps_remote_install_path: "/opt/scala_app"
    language: "scala"
  roles:
    - apps
  become: yes
